package bg.spacbg.sp_ac_bg.model.entity;

import jakarta.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.math.BigDecimal;
import java.time.OffsetDateTime;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "intrastat_settings")
public class IntrastatSettingsEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "company_id", nullable = false)
    private CompanyEntity company;

    @Column(nullable = false)
    private boolean isEnabled;

    @Column(nullable = false, precision = 19, scale = 4)
    private BigDecimal arrivalThresholdBgn;

    @Column(nullable = false, precision = 19, scale = 4)
    private BigDecimal dispatchThresholdBgn;

    @Column(nullable = false, precision = 19, scale = 4)
    private BigDecimal currentArrivalThresholdBgn;

    @Column(nullable = false, precision = 19, scale = 4)
    private BigDecimal currentDispatchThresholdBgn;

    @Column(nullable = false)
    private boolean autoGenerateDeclarations;

    private Integer defaultTransportMode;

    private String defaultDeliveryTerms;

    private String defaultTransactionNature;

    private String responsiblePersonName;

    private String responsiblePersonPhone;

    private String responsiblePersonEmail;

    @CreationTimestamp
    @Column(updatable = false)
    private OffsetDateTime createdAt;

    @UpdateTimestamp
    private OffsetDateTime updatedAt;
}
